### ISSUE TITLE
home items translation

### ISSUE THREAD

**Issue by henrikfur** [kailniris/becreative-website#14]
grid, and text

**Comment by furhenrik** [comment]
**grid:**
1. PRINTED KITCHEN BACKSPLASH
2. KITCHEN ACCESSORIES
3. PRINTED DOORS
4. PRINTED FRIDGE MAGNETS

**text:**

"A sheet of glass can fulfill multiple functions."

**Comment by kailniris** [comment]
https://github.com/kailniris/becreative-website/commit/89b1930f08046b2c0fb16571f46434669060235f
