### ISSUE TITLE
add label to constructor

### ISSUE THREAD

**Issue by furhenrik** [kailniris/becreative-website#35]
![konstruktor1024](https://user-images.githubusercontent.com/29726685/31962990-7ae78fd0-b8ff-11e7-8bcf-9ef0bfbf9cde.jpg)

**Comment by furhenrik** [comment]
![konstruktor1024-2](https://user-images.githubusercontent.com/29726685/31963456-f6701ac2-b900-11e7-9ec3-14ad3d5033a0.jpg)

**Comment by kailniris** [comment]
https://github.com/kailniris/becreative-website/pull/38
