### ISSUE TITLE
"Mi is támogattuk az Alfacity ’16 rendezvényt!" news details

### ISSUE THREAD

**Issue by furhenrik** [kailniris/becreative-website#49]
**details in the wrong place**

now: 
"Mi is támogattuk az Alfacity ’16 rendezvényt!
**Our team visited the Glasstec 2016, the biggest glassmaking exhibition of the world, which took place in Düsseldorf. Between the 20th and 23d of September, almost the whole world had marched up into the enormous exhibition rooms. Workshops, presentations and programs of professional talks followed each other. Also three bigger conferences were held, which topics in 2016 were the "knowhow" platform new functions, the new ways of mechanical applications and research results and the renewable relation of architecture and glass.**"

edit:
"Mi is támogattuk az Alfacity ’16 rendezvényt!
**Évről évre egyre több rajongót vonz az AlfaCity, ahol annyi Alfa Romeo-t láthatsz egy helyen,
amennyire még nem volt példa. 2010-ben például több mint 1000 Alfa járt AlfaCity-ben, de az előző
években is legalább 500 megfordult a helyszínen. Idén abszolút rekordot döntött a 10. AlfaCity-re
ellátogatók száma. Több, mint 1100 autó lépte át a zánkai tábor kapuit.
Munkáink a hivatalos hűtőmágneseken és az információs táblákon:**"

_sent by email: 2017.09.24. 15:45_

**Comment by kailniris** [comment]
https://github.com/kailniris/becreative-website/pull/51
